name: 'my_dbt_project'
version: '1.0.0'

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshot"]

# models:
#   materialized: 'table'
